<?php
namespace AlexScherer\WpthemeValerieknill\Helpers;

class FieldgroupHelper {

    public static function registerFieldGroups() {
        if (function_exists('acf_add_local_field_group')) {
            self::acfRegisterFieldGroups();
        }

    }

    protected static function acfRegisterFieldGroups() {

        acf_add_local_field_group(array(
            'key' => 'group_61556f29bdc34',
            'title' => __('About Page Fieldgroup', 'wptheme-valerieknill'),
            'fields' => array(
                array(
                    'key' => 'field_61556f3a9fd55',
                    'label' => __('About text', 'wptheme-valerieknill'),
                    'name' => 'text_about',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 0,
                    'translations' => 'translate',
                ),
                array(
                    'key' => 'field_61556f5e9fd56',
                    'label' => __('Image', 'wptheme-valerieknill'),
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'translations' => 'copy_once',
                ),
                array(
                    'key' => 'field_61556fb99fd58',
                    'label' => __('Quote', 'wptheme-valerieknill'),
                    'name' => 'quote',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_61556fc89fd59',
                            'label' => __('Name', 'wptheme-valerieknill'),
                            'name' => 'name',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'translations' => 'translate',
                        ),
                        array(
                            'key' => 'field_61556fd09fd5a',
                            'label' => __('Text', 'wptheme-valerieknill'),
                            'name' => 'text',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'translations' => 'translate',
                        ),
                    ),
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'page_about.php',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => array(
                0 => 'the_content',
                1 => 'excerpt',
                2 => 'discussion',
                3 => 'comments',
            ),
            'active' => true,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_61377862f313c',
            'title' => __('Homepage Movies Page Options', 'wptheme-valerieknill'),
            'fields' => array(
                array(
                    'key' => 'field_61377870f28b5',
                    'label' => __('Header Video', 'wptheme-valerieknill'),
                    'name' => 'header_video',
                    'type' => 'file',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'url',
                    'library' => 'all',
                    'min_size' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'translations' => 'copy_once',
                ),
                array(
                    'key' => 'field_6151a786838de',
                    'label' => __('Title', 'wptheme-valerieknill'),
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'translations' => 'translate',
                ),
                array(
                    'key' => 'field_6151a78d838df',
                    'label' => __('Subtitle', 'wptheme-valerieknill'),
                    'name' => 'subtitle',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'translations' => 'translate',
                ),
                array(
                    'key' => 'field_6151a793838e0',
                    'label' => __('Introduction', 'wptheme-valerieknill'),
                    'name' => 'introduction',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'translations' => 'translate',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'page_home.php',
                    ),
                    array(
                        'param' => 'post_taxonomy',
                        'operator' => '==',
                        'value' => 'discipline:film',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => array(
                0 => 'the_content',
                1 => 'excerpt',
                2 => 'discussion',
                3 => 'comments',
            ),
            'active' => true,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_613603a28c2ca',
            'title' => __('Homepage Painting Template Options', 'wptheme-valerieknill'),
            'fields' => array(
                array(
                    'key' => 'field_613604872ce85',
                    'label' => __('Header images', 'wptheme-valerieknill'),
                    'name' => 'header_images',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'collapsed' => '',
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => '',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_613604b12ce86',
                            'label' => __('image', 'wptheme-valerieknill'),
                            'name' => 'image',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'url',
                            'preview_size' => 'medium',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                            'translations' => 'copy_once',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_6139f4adfe80a',
                    'label' => __('Title', 'wptheme-valerieknill'),
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'translations' => 'translate',
                ),
                array(
                    'key' => 'field_6139f4b8fe80b',
                    'label' => __('Subtitle', 'wptheme-valerieknill'),
                    'name' => 'subtitle',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'translations' => 'translate',
                ),
                array(
                    'key' => 'field_6139f4bffe80c',
                    'label' => __('Introduction', 'wptheme-valerieknill'),
                    'name' => 'introduction',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 0,
                    'translations' => 'translate',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'page_home.php',
                    ),
                    array(
                        'param' => 'post_taxonomy',
                        'operator' => '==',
                        'value' => 'discipline:malerei',
                    ),
                ),
                array(
                    array(
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'page_home.php',
                    ),
                    array(
                        'param' => 'post_taxonomy',
                        'operator' => '==',
                        'value' => 'discipline:painting',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'acf_after_title',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => array(
                0 => 'the_content',
                1 => 'excerpt',
                2 => 'discussion',
                3 => 'comments',
                4 => 'featured_image',
            ),
            'active' => true,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_61484ba3d2803',
            'title' => __('Image Fieldgroup', 'wptheme-valerieknill'),
            'fields' => array(
                array(
                    'key' => 'field_61486afbdbd13',
                    'label' => __('Image', 'wptheme-valerieknill'),
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'translations' => 'sync',
                ),
                array(
                    'key' => 'field_61484bdb8ff4c',
                    'label' => __('Dimensions', 'wptheme-valerieknill'),
                    'name' => 'dimensions',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'translations' => 'translate',
                ),
                array(
                    'key' => 'field_61486b0ddbd14',
                    'label' => __('Sold', 'wptheme-valerieknill'),
                    'name' => 'sold',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 0,
                    'translations' => 'copy_once',
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'image',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => array(
                0 => 'the_content',
                1 => 'excerpt',
            ),
            'active' => true,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_61374e3877531',
            'title' => __('Landingpage Fieldgroup', 'wptheme-valerieknill'),
            'fields' => array(
                array(
                    'key' => 'field_61374e490caf7',
                    'label' => __('Title', 'wptheme-valerieknill'),
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'translations' => 'translate',
                ),
                array(
                    'key' => 'field_61374e540caf8',
                    'label' => __('Links', 'wptheme-valerieknill'),
                    'name' => 'links',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'collapsed' => '',
                    'min' => 2,
                    'max' => 2,
                    'layout' => 'table',
                    'button_label' => '',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_61374e6f0caf9',
                            'label' => __('Text', 'wptheme-valerieknill'),
                            'name' => 'text',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'translations' => 'translate',
                        ),
                        array(
                            'key' => 'field_61374e800cafa',
                            'label' => __('Page', 'wptheme-valerieknill'),
                            'name' => 'page_link',
                            'type' => 'page_link',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'post_type' => '',
                            'taxonomy' => '',
                            'allow_null' => 0,
                            'allow_archives' => 1,
                            'multiple' => 0,
                            'translations' => 'copy_once',
                        ),
                        array(
                            'key' => 'field_61374eae0cafb',
                            'label' => __('Image', 'wptheme-valerieknill'),
                            'name' => 'image',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'url',
                            'preview_size' => 'medium',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                            'translations' => 'copy_once',
                        ),
                        array(
                            'key' => 'field_616fd747f5c63',
                            'label' => __('Image position X', 'wptheme-valerieknill'),
                            'name' => 'image_position_x',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'left' => __('Left', 'wptheme-valerieknill'),
                                'center' => __('Center', 'wptheme-valerieknill'),
                                'right' => __('Right', 'wptheme-valerieknill'),
                            ),
                            'default_value' => 'center',
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'return_format' => 'value',
                            'translations' => 'copy_once',
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_616fd7ecf5c64',
                            'label' => __('Image position Y', 'wptheme-valerieknill'),
                            'name' => 'image_position_y',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'top' => __('Top', 'wptheme-valerieknill'),
                                'center' => __('Center', 'wptheme-valerieknill'),
                                'bottom' => __('Bottom', 'wptheme-valerieknill'),
                            ),
                            'default_value' => 'center',
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'return_format' => 'value',
                            'translations' => 'copy_once',
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                    ),
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'page_landingpage.php',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => array(
                0 => 'the_content',
                1 => 'excerpt',
                2 => 'discussion',
                3 => 'comments',
            ),
            'active' => true,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_61448136ce694',
            'title' => __('Menu Crosslink Options', 'wptheme-valerieknill'),
            'fields' => array(
                array(
                    'key' => 'field_61448171b346d',
                    'label' => __('Is Crosslink', 'wptheme-valerieknill'),
                    'name' => 'is_crosslink',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 0,
                    'translations' => 'copy_once',
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'nav_menu_item',
                        'operator' => '==',
                        'value' => 'location/main-menu-painting___en',
                    ),
                ),
                array(
                    array(
                        'param' => 'nav_menu_item',
                        'operator' => '==',
                        'value' => 'location/main-menu-painting',
                    ),
                ),
                array(
                    array(
                        'param' => 'nav_menu_item',
                        'operator' => '==',
                        'value' => 'location/main-menu-film___en',
                    ),
                ),
                array(
                    array(
                        'param' => 'nav_menu_item',
                        'operator' => '==',
                        'value' => 'location/main-menu-film',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_6160020935dc0',
            'title' => __('News Page Fieldgroup', 'wptheme-valerieknill'),
            'fields' => array(
                array(
                    'key' => 'field_6160021965461',
                    'label' => __('Enable Pagination', 'wptheme-valerieknill'),
                    'name' => 'enable_pagination',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 1,
                    'ui' => 0,
                    'translations' => 'copy_once',
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                ),
                array(
                    'key' => 'field_6160025565505',
                    'label' => __('Posts per Page', 'wptheme-valerieknill'),
                    'name' => 'posts_per_page',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 10,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                    'translations' => 'copy_once',
                ),
                array(
                    'key' => 'field_61600bea1e705',
                    'label' => __('Override Author Page', 'wptheme-valerieknill'),
                    'name' => 'override_about_page',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 0,
                    'translations' => 'copy_once',
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                ),
                array(
                    'key' => 'field_61600c0c1e706',
                    'label' => __('Author page', 'wptheme-valerieknill'),
                    'name' => 'about_page_link',
                    'type' => 'page_link',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_61600bea1e705',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => '',
                    'taxonomy' => '',
                    'allow_null' => 0,
                    'allow_archives' => 1,
                    'multiple' => 0,
                    'translations' => 'copy_once',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'page_news.php',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => array(
                0 => 'the_content',
                1 => 'excerpt',
                2 => 'discussion',
                3 => 'comments',
            ),
            'active' => true,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_613f3256e55e6',
            'title' => __('PostType Exhibition Fieldgroup', 'wptheme-valerieknill'),
            'fields' => array(
                array(
                    'key' => 'field_613f33334238d',
                    'label' => __('Name', 'wptheme-valerieknill'),
                    'name' => 'name',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'translations' => 'translate',
                ),
                array(
                    'key' => 'field_613f333b4238e',
                    'label' => __('Image', 'wptheme-valerieknill'),
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'translations' => 'copy_once',
                ),
                array(
                    'key' => 'field_613f33504238f',
                    'label' => __('Description', 'wptheme-valerieknill'),
                    'name' => 'description',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'translations' => 'translate',
                ),
                array(
                    'key' => 'field_613f335b42390',
                    'label' => __('Address', 'wptheme-valerieknill'),
                    'name' => 'address',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => '',
                    'new_lines' => '',
                    'translations' => 'translate',
                ),
                array(
                    'key' => 'field_613f336f3aa12',
                    'label' => __('From', 'wptheme-valerieknill'),
                    'name' => 'from',
                    'type' => 'date_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'd/m/Y',
                    'return_format' => 'd/m/Y',
                    'first_day' => 1,
                    'translations' => 'copy_once',
                ),
                array(
                    'key' => 'field_613f33773aa13',
                    'label' => __('To', 'wptheme-valerieknill'),
                    'name' => 'to',
                    'type' => 'date_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'd/m/Y',
                    'return_format' => 'd/m/Y',
                    'first_day' => 1,
                    'translations' => 'copy_once',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'exhibition',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => array(
                0 => 'the_content',
                1 => 'excerpt',
                2 => 'discussion',
                3 => 'comments',
            ),
            'active' => true,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_61499127a4b11',
            'title' => __('PostType Project Fieldgroup', 'wptheme-valerieknill'),
            'fields' => array(
                array(
                    'key' => 'field_6149a4ed4c35a',
                    'label' => __('Header image', 'wptheme-valerieknill'),
                    'name' => 'header_image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'translations' => 'copy_once',
                ),
                array(
                    'key' => 'field_614c3ec5ca349',
                    'label' => __('Poster image', 'wptheme-valerieknill'),
                    'name' => 'poster_image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'translations' => 'copy_once',
                ),
                array(
                    'key' => 'field_614991377f0ea',
                    'label' => __('Eyecatcher', 'wptheme-valerieknill'),
                    'name' => 'eyecatcher',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_6149919b7f0eb',
                            'label' => __('Type', 'wptheme-valerieknill'),
                            'name' => 'type',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'image_wp' => __('Image from WordPress', 'wptheme-valerieknill'),
                                'video_wp' => __('Video from WordPress', 'wptheme-valerieknill'),
                                'image_link' => __('Image from Link', 'wptheme-valerieknill'),
                                'video_link' => __('Video from Link', 'wptheme-valerieknill'),
                            ),
                            'default_value' => 'image_wp',
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'return_format' => 'value',
                            'translations' => 'copy_once',
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_614992067f0ec',
                            'label' => __('Select File', 'wptheme-valerieknill'),
                            'name' => 'file',
                            'type' => 'file',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_6149919b7f0eb',
                                        'operator' => '==',
                                        'value' => 'image_wp',
                                    ),
                                ),
                                array(
                                    array(
                                        'field' => 'field_6149919b7f0eb',
                                        'operator' => '==',
                                        'value' => 'video_wp',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'url',
                            'library' => 'all',
                            'min_size' => '',
                            'max_size' => '',
                            'mime_types' => '',
                            'translations' => 'copy_once',
                        ),
                        array(
                            'key' => 'field_6149923d7f0ee',
                            'label' => __('Link to file', 'wptheme-valerieknill'),
                            'name' => 'link',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_6149919b7f0eb',
                                        'operator' => '==',
                                        'value' => 'image_link',
                                    ),
                                ),
                                array(
                                    array(
                                        'field' => 'field_6149919b7f0eb',
                                        'operator' => '==',
                                        'value' => 'video_link',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'translations' => 'copy_once',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_6149941f7f6e6',
                    'label' => __('Logline', 'wptheme-valerieknill'),
                    'name' => 'logline',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => '',
                    'new_lines' => 'br',
                    'translations' => 'translate',
                ),
                array(
                    'key' => 'field_6149943b7f6e7',
                    'label' => __('Specifications', 'wptheme-valerieknill'),
                    'name' => 'specifications',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'collapsed' => '',
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => '',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_6149944e7f6e8',
                            'label' => __('Role', 'wptheme-valerieknill'),
                            'name' => 'role',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'translations' => 'translate',
                        ),
                        array(
                            'key' => 'field_614994577f6e9',
                            'label' => __('Name', 'wptheme-valerieknill'),
                            'name' => 'name',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'translations' => 'translate',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_6149948159f0a',
                    'label' => __('Awards', 'wptheme-valerieknill'),
                    'name' => 'awards',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'collapsed' => '',
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => '',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_614995ed59f18',
                            'label' => __('Show on project page', 'wptheme-valerieknill'),
                            'name' => 'show_in_project',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => '',
                            'default_value' => 0,
                            'ui' => 0,
                            'translations' => 'copy_once',
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        array(
                            'key' => 'field_614994a759f0b',
                            'label' => __('Name', 'wptheme-valerieknill'),
                            'name' => 'name',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'translations' => 'translate',
                        ),
                        array(
                            'key' => 'field_614994b659f0c',
                            'label' => __('Plaque', 'wptheme-valerieknill'),
                            'name' => 'plaque',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'preview_size' => 'medium',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                            'translations' => 'copy_once',
                        ),
                        array(
                            'key' => 'field_614995e559f17',
                            'label' => __('Website', 'wptheme-valerieknill'),
                            'name' => 'website',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'translations' => 'copy_once',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_614994c759f0d',
                    'label' => __('Reviews', 'wptheme-valerieknill'),
                    'name' => 'reviews',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'collapsed' => 'field_614994de59f0e',
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'block',
                    'button_label' => '',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_614994de59f0e',
                            'label' => __('Name', 'wptheme-valerieknill'),
                            'name' => 'name',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'translations' => 'translate',
                        ),
                        array(
                            'key' => 'field_614994e859f0f',
                            'label' => __('Source', 'wptheme-valerieknill'),
                            'name' => 'source',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'web' => __('Web', 'wptheme-valerieknill'),
                                'print' => __('Print', 'wptheme-valerieknill'),
                                'none' => __('None', 'wptheme-valerieknill'),
                            ),
                            'default_value' => false,
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'return_format' => 'value',
                            'translations' => 'copy_once',
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_6149953359f10',
                            'label' => __('Source link', 'wptheme-valerieknill'),
                            'name' => 'source_web',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_614994e859f0f',
                                        'operator' => '==',
                                        'value' => 'web',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'translations' => 'copy_once',
                        ),
                        array(
                            'key' => 'field_6149954559f11',
                            'label' => __('Source name', 'wptheme-valerieknill'),
                            'name' => 'source_print',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_614994e859f0f',
                                        'operator' => '==',
                                        'value' => 'print',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'translations' => 'translate',
                        ),
                        array(
                            'key' => 'field_6149955159f12',
                            'label' => __('Content', 'wptheme-valerieknill'),
                            'name' => 'content',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => 1,
                            'delay' => 0,
                            'translations' => 'translate',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_6149958a59f13',
                    'label' => __('Festivals', 'wptheme-valerieknill'),
                    'name' => 'festivals',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'collapsed' => '',
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => '',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_614995a359f14',
                            'label' => __('Name', 'wptheme-valerieknill'),
                            'name' => 'name',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'translations' => 'translate',
                        ),
                        array(
                            'key' => 'field_614995b659f15',
                            'label' => __('Plaque', 'wptheme-valerieknill'),
                            'name' => 'plaque',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'preview_size' => 'medium',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                            'translations' => 'copy_once',
                        ),
                        array(
                            'key' => 'field_614995ca59f16',
                            'label' => __('Website', 'wptheme-valerieknill'),
                            'name' => 'website',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'translations' => 'copy_once',
                        ),
                    ),
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'project',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => array(
                0 => 'the_content',
                1 => 'excerpt',
                2 => 'discussion',
                3 => 'comments',
            ),
            'active' => true,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_61499f6389551',
            'title' => __('Project Archive Fieldgroup', 'wptheme-valerieknill'),
            'fields' => array(
                array(
                    'key' => 'field_61499ff35e72d',
                    'label' => __('Project Archive Settings', 'wptheme-valerieknill'),
                    'name' => 'archive_project',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_6149a03bc91b3',
                            'label' => __('Header Image', 'wptheme-valerieknill'),
                            'name' => 'header_image',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'url',
                            'preview_size' => 'medium',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                            'translations' => 'copy_once',
                        ),
                    ),
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'options_page',
                        'operator' => '==',
                        'value' => 'acf-options-project-archive-settings',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_6139cf5f5c189',
            'title' => __('Slim Header Options', 'wptheme-valerieknill'),
            'fields' => array(
                array(
                    'key' => 'field_6139cf6f5aca3',
                    'label' => __('Header Image', 'wptheme-valerieknill'),
                    'name' => 'header_image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'translations' => 'copy_once',
                ),
                array(
                    'key' => 'field_6143581c295a4',
                    'label' => __('Page title', 'wptheme-valerieknill'),
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'translations' => 'translate',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'page_template',
                        'operator' => '!=',
                        'value' => 'page_home.php',
                    ),
                    array(
                        'param' => 'page_template',
                        'operator' => '!=',
                        'value' => 'page_landingpage.php',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'acf_after_title',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_61484a8ede34b',
            'title' => __('Taxonomy Series Fieldgroup', 'wptheme-valerieknill'),
            'fields' => array(
                array(
                    'key' => 'field_61484aa77c178',
                    'label' => __('Title Image', 'wptheme-valerieknill'),
                    'name' => 'title_image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'translations' => 'copy_once',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'taxonomy',
                        'operator' => '==',
                        'value' => 'series',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_613772a95c8fd',
            'title' => __('Theme Settings', 'wptheme-valerieknill'),
            'fields' => array(
                array(
                    'key' => 'field_613774744dbe3',
                    'label' => __('Disciplines', 'wptheme-valerieknill'),
                    'name' => 'disciplines',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'collapsed' => '',
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => '',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_613774a94dbe4',
                            'label' => __('Term', 'wptheme-valerieknill'),
                            'name' => 'term',
                            'type' => 'taxonomy',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'taxonomy' => 'discipline',
                            'field_type' => 'checkbox',
                            'add_term' => 1,
                            'save_terms' => 0,
                            'load_terms' => 0,
                            'return_format' => 'id',
                            'translations' => 'copy_once',
                            'multiple' => 0,
                            'allow_null' => 0,
                        ),
                        array(
                            'key' => 'field_613774c94dbe5',
                            'label' => __('Discipline', 'wptheme-valerieknill'),
                            'name' => 'discipline',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'painting' => __('Painting', 'wptheme-valerieknill'),
                                'film' => __('Film', 'wptheme-valerieknill'),
                            ),
                            'default_value' => false,
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'return_format' => 'value',
                            'translations' => 'copy_once',
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_6137750760d79',
                            'label' => __('Colorscheme', 'wptheme-valerieknill'),
                            'name' => 'colorscheme',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'green' => __('Green', 'wptheme-valerieknill'),
                                'pink' => __('Pink', 'wptheme-valerieknill'),
                            ),
                            'default_value' => false,
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'return_format' => 'value',
                            'translations' => 'copy_once',
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_6139d7330a7c6',
                    'label' => __('Homepages', 'wptheme-valerieknill'),
                    'name' => 'homepages',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'collapsed' => '',
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => '',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_6139d7580a7c7',
                            'label' => __('Name', 'wptheme-valerieknill'),
                            'name' => 'name',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'translations' => 'translate',
                        ),
                        array(
                            'key' => 'field_6139d7620a7c8',
                            'label' => __('Page', 'wptheme-valerieknill'),
                            'name' => 'page_link',
                            'type' => 'page_link',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'post_type' => '',
                            'taxonomy' => '',
                            'allow_null' => 0,
                            'allow_archives' => 1,
                            'multiple' => 0,
                            'translations' => 'copy_once',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_6164254f10fda',
                    'label' => __('Contact Form', 'wptheme-valerieknill'),
                    'name' => 'contact_form',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_6164256510fdb',
                            'label' => __('Recipient address', 'wptheme-valerieknill'),
                            'name' => 'recipient_email',
                            'type' => 'email',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'translations' => 'copy_once',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_404_hdr_img',
                    'label' => __('404 Header image', 'wptheme-valerieknill'),
                    'name' => 'header_image_404',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'translations' => 'copy_once',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'options_page',
                        'operator' => '==',
                        'value' => 'theme-settings',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
        ));

    }
}
